version: "2"

# networks:
#   my-net:
#     external: true
#     name: my-net
#   ros_net:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 192.168.0.0/24
#           gateway: 192.168.0.1

services:
  ros_core_carto:
    image: jaykor97/freeway:rev.13_arm_jay_carto_hospital
    container_name: ros_core_carto
    # hostname: ros_core_carto
    restart: always
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         count: 1
    #         capabilities: [gpu]
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      # - "NVIDIA_DRIVER_CAPABILITIES=all"
      # - "DISPLAY=$DISPLAY"
      # - "QT_X11_NO_MITSHM=1"
      # - "XAUTHORITY=/tmp/.docker.xauth"
      - "ROS_HOSTNAME=192.168.4.3"
      # - "ROS_IP=192.168.4.3"
      - "ROS_MASTER_URI=http://192.168.4.3:11311"
    volumes:
      - "~/docker_compose/docker_carto_arm/data:/data"
      - "~/docker_compose/docker_carto_arm/map:/robot/map"
      # - "~/docker_compose/docker_carto_arm/param:/robot/param"
      - "~/docker_compose/docker_carto_arm/launch/fw_init:/home/freeway_rev04/src/fw_init"
      - "~/docker_compose/docker_carto_arm/launch/fw_cam:/home/freeway_rev04/src/fw_cam"
      # - "~/docker_compose/docker_carto_arm/launch/fw_rtabmap:/home/freeway_rev04/src/fw_rtabmap"
      - "~/docker_compose/docker_carto_arm/launch/fw_navigation:/home/freeway_rev04/src/fw_navigation"
      # - "/tmp/argus_socket:/tmp/argus_socket"
      #- "/tmp/.X11-unix/:/tmp/.X11-unix:rw"
      #- "/tmp/.docker.xauth:/tmp/.docker.xauth:rw"
    command: ["/bin/zsh", "-c", "source /opt/ros/melodic/setup.zsh; source ~/.zshrc; roscore;"]
    # networks:
    #   ros_net:
    #     ipv4_address: 192.168.4.3
        # my-net:
      #   ipv4_address: 192.168.0.10
    network_mode: host
    # ipc: host
    #restart: always

  fw_init_carto:
    # build: ,,
    image: jaykor97/freeway:rev.13_arm_jay_carto_hospital
    container_name: fw_init_carto
    restart: always
    depends_on:
        - ros_core_carto
    # networks:
    #   ros_net:
    #     ipv4_address: 192.168.0.11
      # my-net:
      #   ipv4_address: 192.168.0.10
    network_mode: host
    # ipc: host
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    privileged: true
    environment:
      - "ROS_HOSTNAME=192.168.4.3"
      - "ROS_MASTER_URI=http://192.168.4.3:11311"
    # command: zsh
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    privileged: true
    environment:
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "XAUTHORITY=/tmp/.docker.xauth"
    volumes:
      - "/dev:/dev"
      # - "/dev/MD:/dev/MD"
      # - "/dev/STMJOY:/dev/STMJOY"
      # - "/dev/MAINJOY:/dev/MAINJOY"
      # - "/dev/RPLIDARS2:/dev/RPLIDARS2"
      - "~/docker_compose/docker_carto_arm/data:/data"
      - "~/docker_compose/docker_carto_arm/map:/robot/map"
      - "~/docker_compose/docker_carto_arm/launch/fw_main_joy:/home/freeway_rev04/src/fw_main_joy"
      - "~/docker_compose/docker_carto_arm/launch/fw_md:/home/freeway_rev03/src/fw/fw_md"
      - "~/docker_compose/docker_carto_arm/launch/fw_richbeam:/home/freeway_rev03/src/fw/fw_richbeam"
      - "~/docker_compose/docker_carto_arm/launch/ira_laser_tools:/home/freeway_rev03/src/fw/ira_laser_tools"
      #  - "~/docker_compose/docker_carto_arm/param:/robot/param"
      - "~/docker_compose/docker_carto_arm/launch/fw_init:/home/freeway_rev04/src/fw_init"
      - "~/docker_compose/docker_carto_arm/launch/fw_cam:/home/freeway_rev04/src/fw_cam"
      - "~/docker_compose/docker_carto_arm/launch/fw_ttc:/home/freeway_rev04/src/fw_ttc"
      # - "~/docker_compose/docker_carto_arm/launch/fw_rtabmap:/home/freeway_rev04/src/fw_rtabmap"
      - "~/docker_compose/docker_carto_arm/launch/fw_navigation:/home/freeway_rev04/src/fw_navigation"
      - "~/docker_compose/docker_carto_arm/launch/fw_semiauto:/home/freeway_rev04/src/fw_semiauto"
      - "~/docker_compose/docker_carto_arm/launch/yocs_velocity_smoother:/home/navigation_ws/src/navigation/yocs_velocity_smoother"
      - "~/docker_compose/docker_carto_arm/launch/yocs_cmd_vel_mux:/home/navigation_ws/src/navigation/yocs_cmd_vel_mux"
    command: ["/bin/zsh", "-c", "source /root/.zshrc; roslaunch --wait fw_rev_04_init fw_robot.launch;"]

  fw_cam_carto_l:
    # build: ,,
    image: jaykor97/freeway:rev.13_arm_jay_carto_hospital
    container_name: fw_cam_carto_l
    restart: always
    depends_on:
        - ros_core_carto
    stdin_open: true # docker run -i
    tty: true        # docker run -t  
    # networks:
    #   ros_net:
    #     ipv4_address: 192.168.0.12
      # my-net:
      #   ipv4_address: 192.168.0.10
    network_mode: host
    # ipc: host
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    privileged: true
    environment:
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "XAUTHORITY=/tmp/.docker.xauth"
      - "ROS_HOSTNAME=192.168.4.3"
      - "ROS_MASTER_URI=http://192.168.4.3:11311"
    # command: zsh
    volumes:
      - "/dev:/dev"
      - "~/docker_compose/docker_carto_arm/data:/data"
      - "~/docker_compose/docker_carto_arm/map:/robot/map"
      # - "~/docker_compose/docker_carto_arm/param:/robot/param"
      - "~/docker_compose/docker_carto_arm/launch/fw_init:/home/freeway_rev04/src/fw_init"
      - "~/docker_compose/docker_carto_arm/launch/fw_cam:/home/freeway_rev04/src/fw_cam"
      # - "~/docker_compose/docker_carto_arm/launch/fw_rtabmap:/home/freeway_rev04/src/fw_rtabmap"
      - "~/docker_compose/docker_carto_arm/launch/fw_navigation:/home/freeway_rev04/src/fw_navigation"
    command: ["/bin/zsh", "-c", "source /root/.zshrc; roslaunch --wait fw_rev_04_cam left.launch;"]


  fw_cam_carto_r:
    # build: ,,
    image: jaykor97/freeway:rev.13_arm_jay_carto_hospital
    container_name: fw_cam_carto_r
    restart: always
    depends_on:
        - ros_core_carto
    stdin_open: true # docker run -i
    tty: true        # docker run -t  
    # networks:
    #   ros_net:
    #     ipv4_address: 192.168.0.12
      # my-net:
      #   ipv4_address: 192.168.0.10
    network_mode: host
    # ipc: host
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    privileged: true
    environment:
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "XAUTHORITY=/tmp/.docker.xauth"
      - "ROS_HOSTNAME=192.168.4.3"
      - "ROS_MASTER_URI=http://192.168.4.3:11311"
    # command: zsh
    volumes:
      - "/dev:/dev"
      - "~/docker_compose/docker_carto_arm/data:/data"
      - "~/docker_compose/docker_carto_arm/map:/robot/map"
      # - "~/docker_compose/docker_carto_arm/param:/robot/param"
      - "~/docker_compose/docker_carto_arm/launch/fw_init:/home/freeway_rev04/src/fw_init"
      - "~/docker_compose/docker_carto_arm/launch/fw_cam:/home/freeway_rev04/src/fw_cam"
      # - "~/docker_compose/docker_carto_arm/launch/fw_rtabmap:/home/freeway_rev04/src/fw_rtabmap"
      - "~/docker_compose/docker_carto_arm/launch/fw_navigation:/home/freeway_rev04/src/fw_navigation"
    command: ["/bin/zsh", "-c", "source /root/.zshrc; roslaunch --wait fw_rev_04_cam right.launch;"]


  # realsense_l:
  #   image: realsense_ros:melodic
  #   container_name: realsense_l
  #   restart: always
  #   depends_on:
  #       - ros_core_carto
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  #   privileged: true
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           count: 1
  #           capabilities: [gpu]
  #   privileged: true
  #   environment:
  #     - "NVIDIA_DRIVER_CAPABILITIES=all"
  #     - "DISPLAY=$DISPLAY"
  #     - "QT_X11_NO_MITSHM=1"
  #     - "XAUTHORITY=/tmp/.docker.xauth"
  #     - "ROS_HOSTNAME=192.168.4.3"
  #     # - "ROS_IP=192.168.4.3"
  #     - "ROS_MASTER_URI=http://192.168.4.3:11311"
  #   volumes:
  #     - "/dev:/dev"
  #     - "~docker_compose/realsense_docker/launch:/opt/ros/melodic/share/realsense2_camera/launch"
  #   command: ["/bin/bash", "-c", "roslaunch --wait realsense2_camera left.launch;"]
  #   network_mode: host

  # realsense_r:
  #   # build: ,,
  #   image: realsense_ros:melodic
  #   container_name: realsense_r
  #   restart: always
  #   depends_on:
  #       - ros_core_carto
  #   network_mode: host
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  #   privileged: true
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           count: 1
  #           capabilities: [gpu]
  #   privileged: true
  #   environment:
  #     - "NVIDIA_DRIVER_CAPABILITIES=all"
  #     - "DISPLAY=$DISPLAY"
  #     - "QT_X11_NO_MITSHM=1"
  #     - "XAUTHORITY=/tmp/.docker.xauth"
  #     - "ROS_HOSTNAME=192.168.4.3"
  #     # - "ROS_IP=192.168.4.3"
  #     - "ROS_MASTER_URI=http://192.168.4.3:11311"
  #   volumes:
  #     - "/dev:/dev"
  #     - "~docker_compose/realsense_docker/launch:/opt/ros/melodic/share/realsense2_camera/launch"
  #   command: ["/bin/bash", "-c", "roslaunch --wait realsense2_camera right.launch;"]
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/aarch64-linux-gnu/tegra

